# Generated by Django 4.1.6 on 2023-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(default='@.com', max_length=254),
            preserve_default=False,
        ),
    ]
